### ISSUE TITLE
Bugsim: reading pod info from cluster failed

### ISSUE THREAD

**Issue by kurthv** [cypherfox/cloud-native-demo#3]
[logs.txt](https://github.com/cypherfox/cloud-native-demo/files/8327186/logs.txt)

**Comment by cypherfox** [comment]
Selecting the namespace is not yet exposed in the cli command, but will be shortly.

The required roles, bindings and service accounts for the namespace 'cloud-native-demo' should already be part of the helm template.

I will keep you posted.
